version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  BeforeInstall: 
    - location: new1.sh
      timeout: 300
  AfterInstall:
    - location: new2.sh
      timeout: 300
